[package]
name = "gio"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["glib", "gio", "gtk-rs", "gnome"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/gio/"
version = "0.7.0"
description = "Rust bindings for the Gio library"
repository = "https://github.com/gtk-rs/gio"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/gio", service = "github" }
travis-ci = { repository = "gtk-rs/gio" }

[lib]
name = "gio"

[features]
v2_44 = ["gio-sys/v2_44", "glib/v2_44"]
v2_46 = ["v2_44", "gio-sys/v2_46", "glib/v2_46"]
v2_48 = ["v2_46", "gio-sys/v2_48", "glib/v2_48"]
v2_50 = ["v2_48", "gio-sys/v2_50", "glib/v2_50"]
v2_52 = ["v2_50", "gio-sys/v2_52", "glib/v2_52"]
v2_54 = ["v2_52", "gio-sys/v2_54", "glib/v2_54"]
v2_56 = ["v2_54", "gio-sys/v2_56", "glib/v2_56"]
v2_58 = ["v2_56", "gio-sys/v2_58", "glib/v2_58"]
dox = ["gio-sys/dox", "glib/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
futures = ["futures-preview", "glib/futures"]
subclassing = ["glib/subclassing"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true

[dependencies]
gobject-sys = "0.9.0"
# gio-sys = "0.9.0"
# glib = "0.8.0"
# glib-sys = "0.9.0"
glib = { git = "https://github.com/cthorner/glib", tag="0.8.0", features=["subclassing"] }
gio-sys = { git = "https://github.com/cthorner/sys", version = "0.9.0" }
libc = "0.2"
bitflags = "1.0"
lazy_static = "1.0"
futures-preview = { version = "0.3.0-alpha", optional = true }
fragile = "0.3"

[dev-dependencies]
gir-format-check = "^0.1"
